# Generated by Django 4.2.2 on 2023-06-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id_comida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('ingredientes', models.TextField()),
                ('foto', models.ImageField(upload_to='comida')),
                ('precio', models.IntegerField(default=0)),
                ('especial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=20)),
                ('titular', models.CharField(max_length=50)),
                ('numero_tarjeta', models.IntegerField()),
                ('codigo_seguridad', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='Usuario')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
    ]
