# Generated by Django 4.1.5 on 2023-06-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comida',
            name='categoria',
        ),
        migrations.AddField(
            model_name='comida',
            name='especial',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
