# Generated by Django 4.2.1 on 2023-07-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
