# Generated by Django 4.2.2 on 2023-07-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_usuario_tarjeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='codigo_seguridad',
        ),
        migrations.AlterField(
            model_name='tarjeta',
            name='numero_tarjeta',
            field=models.BigIntegerField(),
        ),
    ]
