# Generated by Django 4.2.2 on 2023-07-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_tarjeta_codigo_seguridad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='codigo_seguridad',
            field=models.IntegerField(null=True),
        ),
    ]
