# Generated by Django 4.2.2 on 2023-07-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_tarjeta_codigo_seguridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='codigo_seguridad',
            field=models.BigIntegerField(null=True),
        ),
    ]
