# Generated by Django 4.2.2 on 2023-07-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_tarjeta_codigo_seguridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='codigo_seguridad',
            field=models.IntegerField(null=True),
        ),
    ]
