# Generated by Django 4.2.2 on 2023-07-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_alter_tarjeta_numero_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='numero_tarjeta',
            field=models.CharField(max_length=20),
        ),
    ]
