# Generated by Django 4.2.1 on 2023-07-12 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_usuario_direccion'),
        ('menu', '0014_alter_tarjeta_numero_tarjeta'),
    ]

    operations = [
    ]
