# Generated by Django 4.2.1 on 2023-07-12 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_merge_20230711_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tarjeta',
        ),
    ]
